---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: avarteqgmbh/pipeline-utils

inputs:
  - name: chart
  - name: app-release

outputs:
  - name: updated-app

run:
  path: chart/ci/tasks/update-app/task.sh
