---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: avarteqgmbh/pipeline-utils

inputs:
  - name: chart
  - name: version

outputs:
  - name: final-chart-artifacts

run:
  path: chart/ci/tasks/build-final-release/task.sh
